export default [
    {
        files: ['**/*.js'],
        ignores: ['node_modules/**', 'dist/**', 'coverage/**'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'script',
            globals: {
                Blob: 'readonly',
                MutationObserver: 'readonly',
                URL: 'readonly',
                XMLHttpRequest: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                console: 'readonly',
                document: 'readonly',
                getComputedStyle: 'readonly',
                location: 'readonly',
                navigator: 'readonly',
                requestAnimationFrame: 'readonly',
                setInterval: 'readonly',
                setTimeout: 'readonly',
                unsafeWindow: 'readonly',
                window: 'readonly',
                GM_getValue: 'readonly',
                GM_setValue: 'readonly',
                GM_setClipboard: 'readonly',
            },
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': [
                'error',
                {
                    argsIgnorePattern: '^_',
                    caughtErrorsIgnorePattern: '^_',
                },
            ],
            'no-unreachable': 'error',
            'no-constant-condition': ['error', { checkLoops: false }],
            'no-dupe-keys': 'error',
            'no-dupe-args': 'error',
            'no-func-assign': 'error',
            'no-import-assign': 'error',
            'no-self-assign': 'error',
            'no-setter-return': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
        },
    },
];
